#! /bin/sh
#
# Copyright 2010 British Broadcasting Corporation and Kamaelia Contributors(1)
#
# (1) Kamaelia Contributors are listed in the AUTHORS file and at
#     http://www.kamaelia.org/AUTHORS - please extend this file,
#     not this notice.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# /etc/init.d/kamaeliagrey
#
# Untested
#

case "$1" in
  start)
        echo "Starting greylisting daemon"
        runGreylister.sh
        ;;
    stop)
        echo "Currently we don't support killing the greylisting daemon -"
        echo "you have to do this manually - sorry! Improvements to this"
        echo "script are welcome."
        # rc_status -v
        ;;
    status)
        echo "Currently we don't support status checking. Ought to improve this."
        echo "Improvements welcome!"
#        rc_failed 4
#        rc_status -v
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac

